# ASSN_03

Complete the following questions using the flights dataset. Once complete, upload the ipynb file to Blackboard.

## 1. Import the Relevant Data Analysis Packages

Python

In [ ]:
%load_ext rpy2.ipython

In [ ]:
import pandas as pd
import numpy as np

R

In [ ]:
%%R
library(dplyr)
library(tidyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

# 2. Read in the Flights Data, and print out the first 5 rows of the dataset

Python

In [ ]:
flights = pd.read_csv("flights-flights.csv")
flights.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

R

In [ ]:
%%R
flights <- read.csv("flights-flights.csv")
head(flights, 5)

  year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013     1   1      517            515         2      830            819
2 2013     1   1      533            529         4      850            830
3 2013     1   1      542            540         2      923            850
4 2013     1   1      544            545        -1     1004           1022
5 2013     1   1      554            600        -6      812            837
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1        11      UA   1545  N14228    EWR  IAH      227     1400    5     15
2        20      UA   1714  N24211    LGA  IAH      227     1416    5     29
3        33      AA   1141  N619AA    JFK  MIA      160     1089    5     40
4       -18      B6    725  N804JB    JFK  BQN      183     1576    5     45
5       -25      DL    461  N668DN    LGA  ATL      116      762    6      0
             time_hour
1 2013-01-01T10:00:00Z
2 2013-01-01T10:00:00Z
3 2013-01-01T10:00:00Z
4 2013-01-01T10:00:00Z
5 2013-01-01T11:00:00Z

# 3. Write code to find the answers to each question below **seperately**.

- 1a. Had an arrival delay of two or more hours
- 1b. Flew to Houston (IAH or HOU)
- 1c. Were operated by United, American, or Delta
- 1d. Departed in summer (July, August, and September)
- 1e. Arrived more than two hours late, but didn’t leave late
- 1f. Made up at least 60 minutes in flight time (hint.. you need to create a new column)
- 1g. Departed between midnight and 6am (inclusive)

I do not know if you wanted to see the tables or not but I assumed what you were looking for were the values. I have also done it this way since it was taking a long time to load the answer in R specifically. However if the answers are needed in table formats we can just take the " len()" off for python so the len in front and the first parenthesis with the last to have the tables. For R, there was a count function added at the end to count them for us, so we would just take the %>%
count() with the tab off.

Python

In [ ]:
#-- a
len(flights[flights["arr_delay"] >= 120])
 #--Here I am basically asking for them to search flights that had hours greater than 120 minutes.

#-- 10200 flights had a 2hours or more delay.

10200

In [ ]:
#-- b
len(flights[flights["dest"].isin(["IAH", "HOU"])])
 #-- dest gets the different locations while isin is saying to keep it only from IAH and HOU which are the codes fro the locations we are looking for.
 #-- There were 9313 flights from Houston.

In [ ]:
#-- c
len(flights[flights["carrier"].isin(["UA", "AA", "DL"])])
#- There were 139 504 flights from those specific airlines.

139504

In [ ]:
#-- d
len(flights[flights["month"].isin([7, 8, 9])])
#- There were 86 326 flights from July to September.

86326

In [ ]:
#-- e
len(flights[(flights["arr_delay"] > 120) & (flights["dep_delay"] <= 0)])
#- There were 29 flights with a delay more than 2 hours and no departure time delays.

29

In [ ]:
#-- f
flights["time_made_up"] = flights["dep_delay"] - flights["arr_delay"]
len(flights[flights["time_made_up"] >= 60])
#There were 186 flights with a time madeup of 60 minutes or more.

186

In [ ]:
#-- g
len(flights[(flights["dep_time"] >= 0) & (flights["dep_time"] <= 600)])
#- There were 9344 flights with a departure time betweem midnight and 6:00 AM.

9344

R

The same reasonings and informatiosn were found for this exercise in python and R.

In [ ]:
#-- a
%%R
flights %>%
  filter(arr_delay >= 120)%>%
   count()

      n
1 10200

In [ ]:
#-- b
%%R
flights %>%
  filter(dest %in% c("IAH", "HOU"))%>%
   count()

     n
1 9313

In [ ]:
#-- c
%%R
flights %>%
  filter(carrier %in% c("UA", "AA", "DL"))%>%
   count()

       n
1 139504

In [ ]:
#-- d
%%R
flights %>%
  filter(month %in% c(7, 8, 9))%>%
   count()

      n
1 86326

In [ ]:
#-- e
%%R
flights %>%
  filter(arr_delay > 120, dep_delay <= 0)%>%
    count()

   n
1 29

In [ ]:
#-- f
%%R
flights %>%
  mutate(time_made_up = dep_delay - arr_delay) %>%
  filter(time_made_up >= 60) %>%
  count()

    n
1 186

In [ ]:
#-- g
%%R
flights %>%
  filter(dep_time >= 0, dep_time <= 600)%>%
   count()

     n
1 9344

# 4. How many flights have a missing dep_time? What other variables are missing? What might these rows represent?

8255 flights have a missing departure time. The departure delay, arriving time, arrivind delay, tailnum and air time are also missing which could mean that those flights were cancelled and no travels occured for them. There were 2512 tail number missing which meant that those planes did not even get their identification for the flights while the oterhs had it and got cancelled which would be the rest a part of the 8255 flights missing or travelled.

Python

In [ ]:
missing_dep_time = flights["dep_time"].isna().sum()
missing_dep_time

missing_rows = flights[flights["dep_time"].isna()]
missing_summary = missing_rows.isna().sum()
missing_summary

year                 0
month                0
day                  0
dep_time          8255
sched_dep_time       0
dep_delay         8255
arr_time          8255
sched_arr_time       0
arr_delay         8255
carrier              0
flight               0
tailnum           2512
origin               0
dest                 0
air_time          8255
distance             0
hour                 0
minute               0
time_hour            0
time_made_up      8255
dtype: int64

R

In [ ]:
%%R
sum(is.na(flights$dep_time))

missing_rows <- flights %>%
  filter(is.na(dep_time))

colSums(is.na(missing_rows))

          year          month            day       dep_time sched_dep_time
             0              0              0           8255              0
     dep_delay       arr_time sched_arr_time      arr_delay        carrier
          8255           8255              0           8255              0
        flight        tailnum         origin           dest       air_time
             0           2512              0              0           8255
      distance           hour         minute      time_hour
             0              0              0              0

# 5. What is the average departure delay time, for each airline? Who has the lowest? The highest? (hint.. group_by functions should be useful)

The average list of each airlines will be found below but the lowest average was for the US airline while the highest was for the F9 airline.

Python

In [ ]:
# Average departure delay by airline
avg_dep_delay = flights.groupby("carrier", as_index=False)["dep_delay"].mean()

avg_dep_delay.columns = ["carrier", "avg_dep_delay"]

avg_dep_delay

In [ ]:
lowest = avg_dep_delay.loc[avg_dep_delay["avg_dep_delay"].idxmin()]
lowest

carrier                US
avg_dep_delay    3.782418
Name: 12, dtype: object

In [ ]:
highest = avg_dep_delay.loc[avg_dep_delay["avg_dep_delay"].idxmax()]
highest

carrier                 F9
avg_dep_delay    20.215543
Name: 6, dtype: object

R

In [ ]:

%%R
avg_dep_delay <- flights %>%
  group_by(carrier) %>%
  summarise(avg_dep_delay = mean(dep_delay, na.rm = TRUE))

avg_dep_delay

avg_dep_delay %>% slice_min(avg_dep_delay)

avg_dep_delay %>% slice_max(avg_dep_delay)

# A tibble: 1 × 2
  carrier avg_dep_delay
  <chr>           <dbl>
1 F9               20.2

In [ ]:
%%R
avg_dep_delay %>% slice_min(avg_dep_delay)

# A tibble: 1 × 2
  carrier avg_dep_delay
  <chr>           <dbl>
1 US               3.78

In [ ]:
%%R
avg_dep_delay %>% slice_max(avg_dep_delay)

# A tibble: 1 × 2
  carrier avg_dep_delay
  <chr>           <dbl>
1 F9               20.2

# 6., 7., & 8. Create new dataframes, where you...
1. filter the dataset to just American Airlines, Delta, and United Airlines
2. Aggregate the dataset so that only the airline field and year are your only columns, and the count of flights in a given year are the values
3. Widen the dataset so that each airline is its own column

Python

In [ ]:
filtered = flights[flights["carrier"].isin(["AA", "DL", "UA"])]
filtered

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,time_made_up
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z,-9.0
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z,-16.0
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z,-31.0
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z,19.0
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,1696,N39463,EWR,ORD,150.0,719,5,58,2013-01-01T10:00:00Z,-16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336737,2013,9,30,2105.0,2106,-1.0,2329.0,2354,-25.0,UA,475,N477UA,EWR,IAH,175.0,1400,21,6,2013-10-01T01:00:00Z,24.0
336744,2013,9,30,2121.0,2100,21.0,2349.0,14,-25.0,DL,2363,N193DN,JFK,LAX,296.0,2475,21,0,2013-10-01T01:00:00Z,46.0
336751,2013,9,30,2140.0,2140,0.0,10.0,40,-30.0,AA,185,N335AA,JFK,LAX,298.0,2475,21,40,2013-10-01T01:00:00Z,30.0
336755,2013,9,30,2149.0,2156,-7.0,2245.0,2308,-23.0,UA,523,N813UA,EWR,BOS,37.0,200,21,56,2013-10-01T01:00:00Z,16.0
336762,2013,9,30,2233.0,2113,80.0,112.0,30,42.0,UA,471,N578UA,EWR,SFO,318.0,2565,21,13,2013-10-01T01:00:00Z,38.0

In [ ]:
agg = (
    filtered
    .groupby(["carrier", "year"], as_index=False)
    .size()
    .rename(columns={"size": "flight_count"})
)
agg

  carrier  year  flight_count
0      AA  2013         32729
1      DL  2013         48110
2      UA  2013         58665

In [ ]:
wide = agg.pivot(index="year", columns="carrier", values="flight_count").reset_index()
wide

carrier  year     AA     DL     UA
0        2013  32729  48110  58665

R

In [ ]:
%%R
filtered <- flights %>%
  filter(carrier %in% c("AA", "DL", "UA"))
filtered

Streaming output truncated to the last 5000 lines.
1911        -7      UA   1072  N37422    EWR  FLL      164     1065    8     29
1912       -17      AA    717  N3DSAA    LGA  DFW      216     1389    8     35
1913         5      UA    112  N12116    JFK  LAX      332     2475    8     30
1914         0      UA   1626  N33292    EWR  SAN      351     2425    8     40
1915       -13      UA   1202  N37255    EWR  MIA      167     1085    8     47
1916        -7      UA   1110  N76502    LGA  IAH      235     1416    8     47
1917        12      AA   1357  N5FMAA    JFK  SJU      206     1598    8     45
1918       -23      DL   1885  N990DL    LGA  MCO      147      950    9      0
1919        -9      UA    565  N578UA    EWR  LAS      306     2227    8     59
1920       -17      DL    120  N702TW    JFK  LAX      323     2475    9      0
1921       -32      UA   1643  N14121    EWR  DEN      222     1605    9      0
1922       -14      DL    181  N373NW    LGA  DTW       91      502    9      0
1923       -13      DL   1747  N609DL    LGA  ATL      124      762    9      0
1924         8      AA    647  N5EGAA    JFK  MIA      165     1089    9      0
1925        14      AA      1  N327AA    JFK  LAX      344     2475    9      0
1926        10      DL   2379  N317NB    LGA  FLL      186     1076    9      5
1927         2      UA   1519  N15710    EWR  STT      216     1634    9      8
1928        21      UA    673  N855UA    EWR  ORD      117      719    9      0
1929       -27      AA    721  N575AA    LGA  DFW      220     1389    9     20
1930        -6      UA   1529  N73291    EWR  CLE       73      404    9     10
1931       -23      AA   1589  N4WRAA    EWR  DFW      219     1372    9     20
1932       -15      AA   1871  N3GNAA    LGA  MIA      163     1096    9     40
1933        31      UA   1548  N14731    EWR  IAH      222     1400    8     57
1934        -8      AA    319  N566AA    LGA  ORD      122      733    9     45
1935        11      DL   1847  N664DN    LGA  ATL      129      762   10      0
1936       -36      UA   1177  N13718    EWR  EGE      242     1726   10      0
1937       -11      DL   1529  N618DL    JFK  LAS      310     2248   10      0
1938         5      UA    789  N430UA    EWR  FLL      188     1065   10      5
1939        -3      DL   2044  N909DL    LGA  MIA      165     1096   10      0
1940       -16      DL   1765  N727TW    JFK  SFO      347     2586   10      0
1941       -20      UA    499  N438UA    EWR  SEA      340     2402   10      0
1942         6      DL   2319  N980DL    LGA  MSP      150     1020   10     16
1943       -10      UA    680  N432UA    LGA  IAH      225     1416   10     15
1944        -1      DL   1903  N934DL    LGA  SRQ      177     1047   10     21
1945        -1      UA    952  N474UA    EWR  RSW      176     1068   10     18
1946       -27      AA    179  N335AA    JFK  SFO      345     2586   10     30
1947        -5      AA    321  N4WWAA    LGA  ORD      125      733   10     30
1948         0      DL   2343  N339NB    EWR  ATL      128      746   10     30
1949        -5      AA     19  N328AA    JFK  LAX      344     2475   10     30
1950         0      AA    731  N3JRAA    LGA  DFW      211     1389   10     20
1951        53      DL   1174  N329NB    LGA  PBI      175     1035   10     40
1952       -12      DL   1573  N336NW    LGA  MEM      156      963   10     45
1953       -21      UA    448  N580UA    EWR  LAS      304     2227   10     47
1954        12      UA    518  N674UA    EWR  IAH      217     1400   10     47
1955       -32      UA    642  N508UA    JFK  SFO      347     2586   11      0
1956        10      UA   1580  N34282    EWR  PBI      165     1023   10     54
1957         7      DL   1647  N638DL    LGA  ATL      125      762   11      0
1958       -39      UA   1298  N77525    EWR  SFO      341     2565   10     59
1959        14      AA   2099  N3EGAA    LGA  MIA      172     1096   11     15
1960       -14      DL   1031  N336NB    LGA  DTW       87      502   11     14
1961         7      DL   1275   N3765    JFK  SLC      291     1990   11      0
1962       -20      DL    315   N3753    JFK  SJU      194     1598   11     25
1963       -10      AA    327  N3DCAA    LGA  ORD      121      733   11     25
1964        -9      DL    695  N905DL    JFK  MCO      152      944   11     30
1965        -2      UA    703  N554UA    JFK  LAX      346     2475   11     30
1966        -9      UA    980  N409UA    EWR  DEN      224     1605   11     26
1967       -14      DL   2219  N327NB    LGA  MSP      147     1020   11     34
1968        25      AA   1623  N3GBAA    EWR  MIA      172     1085   11     40
1969        14      UA   1000  N33132    EWR  MCO      156      937   11     30
1970        15      UA   1707  N14214    EWR  TPA      170      997   11     32
1971        26      DL    930  N353NB    LGA  FLL      186     1076   11     40
1972        13      DL   1875  N906DL    LGA  TPA      164     1010   11     45
1973       -29      DL    863  N711ZX    JFK  LAX      337     2475   12      0
1974        25      UA   1283  N76254    EWR  SJU      201     1608   11     25
1975        -7      AA      3  N324AA    JFK  LAX      344     2475   12      0
1976       -18      AA    743  N577AA    LGA  DFW      217     1389   12      5
1977        -1      DL   1947  N555NW    LGA  ATL      126      762   12      0
1978       -15      UA     73  N79279    EWR  SFO      355     2565   12      0
1979         2      UA   1722  N76508    EWR  IAH      220     1400   12      3
1980       -10      UA   1227  N77430    EWR  PHX      302     2133   12     16
1981        -6      AA   1757  N551AA    LGA  STL      140      888   12     20
1982       -16      UA   1623  N78509    LGA  IAH      223     1416   12     30
1983       -18      DL   1131  N358NB    LGA  DTW       95      502   12     40
1984        13      UA    238  N503UA    EWR  MIA      166     1085   12     20
1985       -16      AA   1850  N3HPAA    JFK  BOS       38      187   12     45
1986       -10      AA   1853  N471AA    EWR  DFW      208     1372   12     40
1987       -12      AA   2253  N3HFAA    LGA  MIA      165     1096   12     45
1988       174      UA   1142  N74856    EWR  LAX      324     2454    9     20
1989        -4      AA   2041  N615AA    JFK  MIA      164     1089   12     40
1990       -13      DL   1685  N350NA    LGA  MCO      151      950   12     50
1991        -7      UA    744  N851UA    EWR  DFW      223     1372   12     50
1992        -9      AA    745  N3GXAA    LGA  DFW      210     1389   12     45
1993       -14      AA    329  N478AA    LGA  ORD      120      733   13      0
1994         3      UA   1641  N79402    EWR  MCO      152      937   13      5
1995         0      DL   2043  N3734B    JFK  ATL      126      760   13     30
1996       -24      AA    753  N3GGAA    LGA  DFW      212     1389   13     30
1997        11      UA   1272  N14115    EWR  LAX      330     2454   13     15
1998       -10      AA   1073  N3GAAA    LGA  MIA      169     1096   13     45
1999        -1      AA    117  N322AA    JFK  LAX      342     2475   13     45
2000       -20      DL   1705  N344NB    LGA  MSY      190     1183   13     50
2001        28      UA   1137  N17104    EWR  ORD      116      719   12     59
2002        21      DL   2079  N357NW    LGA  FLL      184     1076   13     55
2003        26      UA    620  N576UA    EWR  FLL      184     1065   13     50
2004       -14      UA     15  N69063    EWR  HNL      610     4963   13     41
2005        12      UA   1604  N87527    EWR  IAH      218     1400   13     55
2006        -3      DL   2247  N665DN    LGA  ATL      123      762   14      0
2007         8      UA   1122  N37434    EWR  PBI      165     1023   13     59
2008        10      DL    935  N348NB    EWR  ATL      127      746   14     15
2009         5      UA   1166  N21108    EWR  TPA      156      997   14     20
2010       -22      UA    560  N518UA    JFK  SFO      348     2586   14     30
2011        -9      AA    883  N591AA    EWR  DFW      203     1372   14     30
2012       -18      DL   1819  N916DN    LGA  MSP      151     1020   14     29
2013       -10      DL   1344  N361NB    LGA  MCI      170     1107   14     35
2014        -8      DL   1902  N324NB    LGA  PBI      163     1035   14     35
2015       -16      UA    459  N839UA    EWR  ORD      117      719   14     35
2016       -19      DL   2126  N713TW    JFK  SFO      343     2586   14     30
2017         7      UA    275  N485UA    LGA  IAH      224     1416   14     44
2018        -8      UA   1418  N24715    EWR  AUS      235     1504   14     43
2019       -21      AA   1813  N5EUAA    JFK  MCO      144      944   14     50
2020       -20      UA    256  N567UA    EWR  DEN      222     1605   14     45
2021        -2      UA   1183  N78501    EWR  RSW      165     1068   14     40
2022        28      AA   1769  N5BVAA    JFK  MIA      161     1089   14     55
2023        18      DL   1231  N944DL    LGA  DTW       86      502   14     52
2024         3      UA    268  N838UA    EWR  BOS       40      200   14     40
2025         7      DL   2347  N617DL    LGA  ATL      125      762   15      0
2026       -18      AA   1925  N3BGAA    LGA  MIA      163     1096   15      0
2027        -3      DL    963  N717TW    JFK  LAX      345     2475   15      0
2028        18      UA   1601  N37427    EWR  FLL      180     1065   14     59
2029       -32      UA    745  N584UA    LGA  DEN      221     1620   15     11
2030       -11      AA    759  N3GUAA    LGA  DFW      213     1389   15      5
2031        13      UA    750  N535UA    EWR  MCO      142      937   15     10
2032       -12      UA    279  N458UA    EWR  ORD      116      719   15      4
2033        -8      UA   1285  N17128    EWR  LAX      335     2454   15      6
2034        50      UA    404  N571UA    EWR  MIA      165     1085   14     34
2035         0      AA    337  N597AA    LGA  ORD      118      733   14     55
2036         6      DL   2115  N369NW    LGA  MIA      177     1096   15     20
2037        -7      AA   2223  N4UBAA    LGA  STL      147      888   15     30
2038        42      AA   1039  N3FHAA    JFK  FLL      173     1069   15     30
2039       -25      AA    763  N3ETAA    LGA  DFW      205     1389   15     35
2040       -10      UA    161  N14102    JFK  LAX      328     2475   15     30
2041        -5      UA   1710  N73251    LGA  CLE       78      419   15     36
2042        41      UA   1205  N67058    EWR  IAH      204     1400   15     15
2043       -10      DL   1942  N326NB    EWR  ATL      126      746   15     45
2044         2      DL   2027  N337NW    JFK  FLL      173     1069   15     40
2045        -4      DL   2377  N370NW    LGA  MCO      155      950   15     45
2046        -8      DL   1773  N3769L    JFK  SLC      289     1990   15     50
2047       -19      AA    133  N338AA    JFK  LAX      332     2475   15     45
2048        12      DL     95  N387DA    JFK  ATL      139      760   15     48
2049       -18      UA    581  N462UA    EWR  BOS       37      200   15     39
2050        13      UA   1624  N78511    EWR  FLL      171     1065   15     45
2051        -2      AA   1635  N5CYAA    JFK  SJU      201     1598   15     50
2052         9      DL    847  N627DL    LGA  ATL      125      762   16      0
2053        -8      DL   1695  N366NW    LGA  TPA      168     1010   15     55
2054        -3      DL   1771  N371NB    JFK  DTW       92      509   15     55
2055        -5      DL      4   N3752    JFK  MCO      145      944   16      0
2056       -14      DL   1331  N382DA    JFK  DEN      238     1626   16      0
2057        -7      AA   1467  N3FUAA    LGA  MIA      167     1096   16      0
2058         8      DL     91  N175DN    JFK  LAS      321     2248   16     10
2059        13      DL    161  N912DE    JFK  MIA      175     1089   16      0
2060       -15      DL   1508  N970DL    JFK  RSW      180     1074   16      5
2061       -15      UA    562  N416UA    EWR  ORD      117      719   16      0
2062       -15      AA    341  N487AA    LGA  ORD      122      733   16     10
2063        -9      AA    565  N3CLAA    JFK  DFW      211     1391   16      0
2064        26      AA     85  N364AA    JFK  SFO      350     2586   15     30
2065        22      UA   1111  N31412    EWR  SFO      341     2565   15     15
2066       -42      DL   1619  N377NW    LGA  MSP      146     1020   16     15
2067       -15      DL   2231  N360NW    LGA  DTW       88      502   16     30
2068         8      UA   1178  N68160    EWR  IAH      214     1400   16     30
2069        16      UA   1197  N71411    EWR  LAS      306     2227   15     55
2070        -7      UA   1719  N35260    EWR  CLE       65      404   16     33
2071        25      UA   1200  N78524    EWR  SAN      330     2425   15     50
2072        16      UA   1262  N39450    EWR  MCO      148      937   16     27
2073       -13      AA    181  N320AA    JFK  LAX      338     2475   16     45
2074       -20      UA   1163  N37255    EWR  SAT      234     1569   16     44
2075        -1      UA    627  N803UA    EWR  ORD      115      719   16     48
2076       -39      DL    706  N336NB    JFK  AUS      226     1521   16     55
2077       -36      AA   1790  N3AVAA    JFK  BOS       33      187   16     50
2078       -15      DL   1473  N317NB    LGA  MEM      157      963   16     45
2079         4      AA    773  N483AA    LGA  DFW      206     1389   16     40
2080       -20      DL   1499  N610DL    LGA  ATL      124      762   17      0
2081       -30      DL    329   N3759    JFK  SJU      196     1598   17      0
2082       -27      UA    741  N831UA    LGA  ORD      115      733   17      0
2083       -11      DL    127  N703TW    JFK  LAX      349     2475   17      0
2084       -17      AA   1905  N4WLAA    EWR  DFW      215     1372   17      5
2085       -30      DL     31  N721TW    JFK  SFO      348     2586   17      0
2086       -12      AA    257  N3GEAA    JFK  LAS      317     2248   17      0
2087        -7      DL   2042  N310DE    EWR  ATL      120      746   17      0
2088       -14      AA    695  N3HPAA    JFK  AUS      216     1521   17     10
2089       -30      DL    503  N3751B    JFK  SAN      333     2446   17     15
2090       -27      UA    531  N417UA    EWR  BOS       36      200   17      7
2091       -18      UA   1615  N14237    EWR  LAS      305     2227   17     10
2092       -23      AA   1999  N5EGAA    EWR  MIA      159     1085   17     20
2093         3      AA    575  N5DSAA    JFK  EGE      255     1747   17      0
2094         3      DL   1779  N322US    LGA  FLL      176     1076   17     20
2095       -13      UA    512  N532UA    JFK  SFO      353     2586   17     25
2096       -17      DL   1185  N3731T    EWR  SLC      268     1969   17     29
2097        14      UA   1134  N41135    EWR  IAH      212     1400   17     25
2098        17      UA   1284  N14107    EWR  SFO      342     2565   17      6
2099        28      UA    508  N480UA    LGA  IAH      218     1416   17      0
2100        -5      AA    345  N4XSAA    LGA  ORD      114      733   17     20
2101        27      UA   1109  N18112    EWR  MCO      150      937   17     30
2102       -25      DL   2331  N980DL    LGA  DTW       78      502   17     45
2103         8      AA   1351  N3DCAA    JFK  ORD      121      740   17     20
2104         9      UA    509  N537UA    LGA  DEN      224     1620   17     24
2105       -24      AA    785  N3JSAA    LGA  DFW      204     1389   17     45
2106       -22      UA    535  N557UA    JFK  LAX      334     2475   17     51
2107         5      AA    177  N325AA    JFK  SFO      354     2586   17     45
2108        34      DL   1585  N996DL    LGA  MCO      151      950   17     15
2109       -13      UA   1228  N54711    EWR  SAN      334     2425   17     50
2110        -2      DL   1394  N3744F    JFK  PDX      351     2454   17     45
2111        13      UA   1637  N76514    EWR  TPA      168      997   17     54
2112        -5      DL   1047  N645DL    LGA  ATL      124      762   18      0
2113         8      AA    145  N363AA    JFK  SAN      323     2446   17     25
2114        -9      AA   1611  N3GNAA    LGA  MIA      173     1096   18     10
2115       -22      UA    709  N822UA    EWR  DFW      194     1372   18      4
2116        39      AA    543  N354AA    JFK  MIA      170     1089   17     29
2117       -32      AA    119  N3BKAA    EWR  LAX      326     2454   18     20
2118        -5      DL    926  N306DQ    EWR  ATL      118      746   18     15
2119        -7      UA    979  N818UA    EWR  PHX      296     2133   18     10
2120        61      UA   1222  N27205    EWR  LAX      327     2454   17      2
2121        27      UA   1053  N27724    EWR  CLE       71      404   18     11
2122       -13      DL   2019  N316US    LGA  MSP      146     1020   18     15
2123        36      UA   1165  N12221    EWR  LAX      330     2454   18     15
2124        -4      AA    269  N3HNAA    JFK  SEA      354     2422   18     30
2125        46      UA    326  N402UA    EWR  ORD      106      719   18      4
2126       -21      UA    272  N505UA    JFK  SFO      336     2586   18     30
2127        48      UA   1612  N78448    EWR  SEA      342     2402   18     15
2128         7      DL   1643  N3771K    JFK  SEA      354     2422   18     35
2129        14      UA   1656  N16709    EWR  SNA      341     2434   18     19
2130        26      UA    428  N474UA    EWR  DEN      222     1605   18     15
2131       -34      DL   2190  N315US    JFK  MIA      167     1089   18     45
2132        -9      DL   2131  N335NW    LGA  DTW       86      502   18     40
2133       -31      AA   2019  N4WTAA    LGA  STL      136      888   18     50
2134       -28      DL   2159  N391DA    JFK  MCO      145      944   18     50
2135        -6      DL   2391  N342NW    JFK  TPA      176     1005   18     55
2136        28      UA   1703  N27213    EWR  BOS       41      200   18     31
2137        27      AA   1613  N5EBAA    JFK  SJU      203     1598   18     55
2138       -18      AA     21  N339AA    JFK  LAX      320     2475   19      5
2139       -37      DL   1255  N349NB    LGA  PIT       63      335   19      0
2140       -19      DL     87  N702TW    JFK  LAX      332     2475   19      0
2141        -3      UA   1675  N14250    LGA  IAH      218     1416   18     51
2142       -13      DL    947  N900PC    LGA  ATL      123      762   19      0
2143       -41      DL   1465  N723TW    JFK  SFO      340     2586   19      0
2144       -10      AA   2075  N4YLAA    EWR  DFW      194     1372   19     10
2145       -27      AA    359  N3JRAA    LGA  ORD      112      733   19     20
2146        11      DL    951  N1613B    JFK  ATL      122      760   18     55
2147       -38      DL   1345  N398DA    JFK  PHX      295     2153   19     20
2148       -25      DL     83  N386DA    JFK  FLL      158     1069   19     20
2149         2      DL   1485  N906DL    LGA  MCO      163      950   19     25
2150        12      UA   1607  N76522    EWR  PBI      159     1023   19     15
2151        -4      DL   2139  N909DL    LGA  MIA      178     1096   19     25
2152        -2      DL   1435  N961DL    LGA  TPA      174     1010   19     30
2153       -39      DL   1729  N679DA    JFK  LAS      302     2248   19     25
2154         2      DL   1854  N364NB    LGA  FLL      176     1076   19     30
2155       -14      DL   1715  N329NB    LGA  MSY      194     1183   19     30
2156        74      UA    347  N460UA    EWR  LAS      304     2227   19     10
2157         0      UA   1574  N18220    EWR  FLL      166     1065   19     32
2158        26      UA   1669  N12225    EWR  SJU      211     1608   19     15
2159         4      AA   1787  N3GMAA    JFK  TPA      170     1005   19     40

In [ ]:
agg <- filtered %>%
  group_by(carrier, year) %>%
  summarise(flight_count = n(), .groups = "drop")
agg

In [ ]:
wide <- agg %>%
  pivot_wider(names_from = carrier, values_from = flight_count)

wide

# 9. Clean up the column names of the original flights dataset, to make it more human readable

Python

In [ ]:
flights_clean = flights.rename(columns={
    "dep_time": "departure_time",
    "arr_time": "arrival_time",
    "dep_delay": "departure_delay",
    "arr_delay": "arrival_delay",
    "carrier": "airline",
    "dest": "destination",
    "air_time": "air_time_minutes"
})

flights_clean.head()

,year,month,day,departure_time,sched_dep_time,departure_delay,arrival_time,sched_arr_time,arrival_delay,airline,flight,tailnum,origin,destination,air_time_minutes,distance,hour,minute,time_hour,time_made_up
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z,-9.0
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z,-16.0
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z,-31.0
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z,17.0
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z,19.0

R

In [ ]:
%%R
flights_clean <- flights %>%
  rename(
    departure_time = dep_time,
    arrival_time = arr_time,
    departure_delay = dep_delay,
    arrival_delay = arr_delay,
    airline = carrier,
    destination = dest,
    air_time_minutes = air_time
  )

head(flights_clean)

  year month day departure_time sched_dep_time departure_delay arrival_time
1 2013     1   1            517            515               2          830
2 2013     1   1            533            529               4          850
3 2013     1   1            542            540               2          923
4 2013     1   1            544            545              -1         1004
5 2013     1   1            554            600              -6          812
6 2013     1   1            554            558              -4          740
  sched_arr_time arrival_delay airline flight tailnum origin destination
1            819            11      UA   1545  N14228    EWR         IAH
2            830            20      UA   1714  N24211    LGA         IAH
3            850            33      AA   1141  N619AA    JFK         MIA
4           1022           -18      B6    725  N804JB    JFK         BQN
5            837           -25      DL    461  N668DN    LGA         ATL
6            728            12      UA   1696  N39463    EWR         ORD
  air_time_minutes distance hour minute            time_hour
1              227     1400    5     15 2013-01-01T10:00:00Z
2              227     1416    5     29 2013-01-01T10:00:00Z
3              160     1089    5     40 2013-01-01T10:00:00Z
4              183     1576    5     45 2013-01-01T10:00:00Z
5              116      762    6      0 2013-01-01T11:00:00Z
6              150      719    5     58 2013-01-01T10:00:00Z

## 10. Use the following data and create a new dataset merging both artist datasets and the instruments dataset together (only R)

On the assignment files you will see csv files named `band_instruments.csv` and `band_members.csv`. Members of the rock bands *The Beatles* and *The Bangles*. Read them into dataframes and then merge them together to produce a new dataframe. You should merge them on 'name' (in band_instruments.csv) and 'artist' (in band_members.csv).

In [ ]:

%%R
band_instruments <- read.csv("band_instruments - band_instruments.csv")
band_members <- read.csv("band_members.csv")

# Merge the data together following the condition that the artist in the first file = to the name in the second.
merged_band_data <- band_members %>%
  left_join(band_instruments, by = c("artist" = "name"))

merged_band_data

   artist    band                                instrument
1 Susanna Bangles                         guitar and vocals
2   Vicki Bangles                         guitar and vocals
3   Debbi Bangles                          drums and vocals
4 Annette Bangles                    bass guitar and vocals
5 Michael Bangles bass guitar and vocals, occasional guitar
6    John Beatles                  rhythm guitar and vocals
7    Paul Beatles                    bass guitar and vocals
8  George Beatles                    lead guitar and vocals
9   Ringo Beatles                          drums and vocals